[singular]
binary_plus = "+"
binary_minus = "-"
binary_mod = "%"
other_asterisk = "*"
other_slash = "/"
other_backslash = '\'
other_semicolon = ";"
other_colon = ":"
other_bang = "!"
other_tilda = "~"
other_dot = "."
other_dollar = "$"
logic_less_than = "<"
logic_greater_than = ">"
group_paren_left = "("
group_paren_right = ")"
group_brace_left = "{"
group_brace_right = "}"
group_bracket_left = "["
group_bracket_right = "]"
assign = "="
[double]
logic_less_or_equal = "<="
logic_greater_or_equal = ">="
logic_equals = "=="
logic_not_equals = "!="
logic_and = "&&"
logic_or = "||"
arrow = "->"
[keyword]
logic_true = "true"
logic_false = "false"
var = "var"
var_map = "map"
null = "null"
modifier_static = "static"
modifier_final = "final"
modifier_private = "private"
modifier_override = "override"
class_package = "package"
class_import = "import"
class_extends = "extends"
word_if = "if"
word_else = "else"
word_return = "return"
word_exit = "exit"
loop_for = "for"
loop_while = "while"
[other]
string = "string"
number = "number"
ident = "ident"
eof = "eof"